DROP TABLE USER_AUTHENTICATION;
DROP TABLE BOOK_AUTHOR_RELATIONS;
DROP TABLE AUTHOR;
DROP TABLE BOOK;

CREATE TABLE USER_AUTHENTICATION(
    USER_NAME VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    EMAIL_ADDRESS VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE AUTHOR(
    ID BIGINT PRIMARY KEY NOT NULL UNIQUE,
    NAME VARCHAR(15) NOT NULL,
    SURNAME VARCHAR(20) NOT NULL,
    BIRTH_YEAR VARCHAR(4),
    DEATH_YEAR VARCHAR(4),
    IMAGE BYTEA,
    DESCRIPTION VARCHAR(5000),
    GENRES VARCHAR
);

CREATE TABLE BOOK(
    ISBN VARCHAR(13) PRIMARY KEY NOT NULL UNIQUE,
    TITLE VARCHAR NOT NULL,
    ORIGINAL_TITLE VARCHAR,
    RELEASE_YEAR VARCHAR(4) NOT NULL,
    GENRES VARCHAR,
    DESCRIPTION VARCHAR(5000),
    COUNTRY_CODE VARCHAR NOT NULL,
    COVER_IMAGE BYTEA
);

CREATE TABLE BOOK_AUTHOR_RELATIONS(
    ID BIGINT PRIMARY KEY NOT NULL UNIQUE,
    BOOK_ID VARCHAR(13) NOT NULL REFERENCES BOOK(ISBN),
    AUTHOR_ID BIGINT NOT NULL REFERENCES AUTHOR(ID)
);