DROP TABLE USER_AUTHENTICATION;
CREATE TABLE USER_AUTHENTICATION(
    USER_NAME VARCHAR(20) PRIMARY KEY NOT NULL UNIQUE,
    PASSWORD VARCHAR(60) NOT NULL,
    EMAIL_ADDRESS VARCHAR(30) NOT NULL UNIQUE
);
